### PR TITLE
Restructure landing page

### LINKED ISSUE #8: Restructure landing page
### Description
The landing page is not crisp enough to help visitors get a grip on Eiffel quickly. We should take the graphical design from Eiffel repos on Github. Also, we should add some interesting pictures to sharpen the message.
- What is Eiffel? with read more links to history etc.
- Getting started
- Contact info link
- Remove details about eco system repos available except some main repos maybe.
- Remove repo status

### Motivation
Easier to get a grip on what Eiffel is and how to try it out

### Exemplification
-

### Benefits
See Motivation

### Possible Drawbacks
-

### PR DESCRIPTION
**Pull request by e-pettersson-ericsson**
### Applicable Issues
Fixes #8 

### Description of the Change
* Move outdated information from summit page to archive 
* Change design theme (red,gray,black) to fit Eiffel logo
    - Fix indentation of list items
    - Update splash image to match the new color scheme
    - Change link color 
    - Update links in navigation menu + footer
* Change logo in header
* Add new "slogan" about Eiffel on index.html
* Reorder information sections on index.html
* Add embedded YouTube video on index.html
* Update contact information to include Slack

Preview is available here: https://e-pettersson-ericsson.github.io/eiffel-community.github.io/ 

### Possible Drawbacks
Sepia repository does not follow the same design theme yet, so in time it might also need to be updated.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by:

### CODE REVIEW

**Comment by d-stahl-ericsson** [comment]
Happy to see more competent hands than mine taking this on!

**Comment by e-backmark-ericsson** [comment]
This looks good to me as well. We should wait a while before merging it though, to give others in the community a chance to comment on it.

**Comment by e-backmark-ericsson** [comment]
It would be great to also have the same red color on the circles in the favicon.ico, shown in the browse tabs.

**Comment by e-pettersson-ericsson** [comment]
> It would be great to also have the same red color on the circles in the favicon.ico, shown in the browse tabs.

Good idea - I'll try and fix that

**Comment by e-backmark-ericsson** [comment]
Looks good!

**Pull request merged**
