### PR TITLE
Summit: Add links to slide decks and videos

### PR DESCRIPTION
**Pull request by magnusbaeck**
### Applicable Issues
N/A; trivial

### Description of the Change
All slide decks added in https://github.com/eiffel-community/community/pull/110 and https://github.com/eiffel-community/community/pull/111 are getting links from https://eiffel-community.github.io/summit.html. Also adding links to all YouTube videos except one. **Do not merge until https://github.com/eiffel-community/community/pull/111 has been merged.**

### Alternate Designs
Considered adding the slide link as a new table cell (alongside the difficulty level) but decided that it would be unnecessarily prominent and wouldn't fit well with the _What's cooking_ session where there were three speakers.

### Benefits
Makes it easier to locate presentation slides and videos.

### Possible Drawbacks
None.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I    have the right to submit it under the open source license    indicated in the file; or

(b) The contribution is based upon previous work that, to the best    of my knowledge, is covered under an appropriate open source    license and I have the right under that license to submit that    work with modifications, whether created in whole or in part    by me, under the same open source license (unless I am    permitted to submit under a different license), as indicated    in the file; or

(c) The contribution was provided directly to me by some other    person who certified (a), (b) or (c) and I have not modified    it.

(d) I understand and agree that this project and the contribution    are public and that a record of the contribution (including all    personal information I submit with it, including my sign-off) is    maintained indefinitely and may be redistributed consistent with    this project or the open source license(s) involved.

Signed-off-by: Magnus Bäck \<magnus.back@axis.com>

### CODE REVIEW

**Review by t-persson — APPROVED** [review]

**Comment by e-backmark-ericsson** [comment]
Is there a preview site available, like the one Mattias brought up in another PR (https://github.com/eiffel-community/eiffel-community.github.io/pull/22)? It's a bit hard to validate the Youtube and pdf links without it.

**Comment by magnusbaeck** [comment]
Not sure how previous sites work. I'll look into it. I've manually verified that all links work and lead to the correct slide deck or video.

**Comment by e-backmark-ericsson** [comment]
Never mind. It would be good to know for the future though. We can ask Mattias on next weeks TC.

**Review by e-backmark-ericsson — APPROVED** [review]

**Comment by magnusbaeck** [comment]
It was, unsurprisingly, documented (see https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site). It's just a matter of enabling publishing from the PR branch in the settings of my repo.

**Comment by magnusbaeck** [comment]
Oh, and now it's actually available: https://magnusbaeck.github.io/eiffel-community.github.io/summit.html

**Review by t-persson — APPROVED** [review]

**Comment by magnusbaeck** [comment]
Sigh, I got the wrong URL for Kristofer's presentation despite copying and pasting. Fixed in an amended commit.

**Pull request merged**
